version: '2'

# node application for ynu-opendoor-api
services:
    ynu-opendoor-api:
        build: .
        ports:
            - '3000'
        environment:
            - DATABASE_HOST
            - DATABASE_PORT
            - DATABASE_USER
            - DATABASE_PASSWORD
            - DATABASE_DATABASE
            - JWT_PRIVATE_KEY
            - USERNAME
            - PASSWORD
            - VIRTUAL_HOST=ynu-opendoor-api.ynu.edu.cn
            - NODE_ENV=production
        restart: always
