version: '3'

services:
    opendoor-backend:
        build: .
        image: liudonghua123/opendoor-backend
        ports:
            - "50091:5000"
        environment:
            - BACKEND_HOST=10.191.51.202
            - BACKEND_PORT=60000
        restart: always
