version: '3'

services:
    opendoor-backend:
        build: .
        image: liudonghua123/opendoor-backend
        ports:
            - "5000:5000"
        environment:
            - BACKEND_HOST=
            - BACKEND_PORT=
        restart: always